from __future__ import annotations

import asyncio
import uuid
from collections.abc import Callable

from git import Repo as GitRepo

from bugops.clients.github_client import GitHubClient
from bugops.config import Settings
from bugops.git import branch_ops, local_repo, worktree
from bugops.logging import get_logger
from bugops.state import BugOpsState

logger = get_logger(__name__)

ApproveFn = Callable[[BugOpsState], bool]


def default_approve(state: BugOpsState) -> bool:
    """Production approval gate: prints a summary and asks via rich's Confirm.ask. Imports rich
    lazily so tests injecting a fake `approve` never touch stdin."""
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm

    console = Console()
    issue = state["issue"]
    hypotheses = state.get("hypotheses", [])
    hypothesis_summary = hypotheses[-1]["summary"] if hypotheses else "(none)"
    confidence = state.get("confidence") or 0.0
    console.print(
        Panel(
            f"confidence: {confidence:.2f}   risk: {state.get('risk_category')}\n"
            f"hypothesis: {hypothesis_summary}\n\n{state.get('current_diff', '')}",
            title=f"Open draft PR for {issue.short_id}?",
        )
    )
    return Confirm.ask("Open this PR?", default=False)


def _branch_name(settings: Settings, state: BugOpsState) -> str:
    return f"{settings.pr_branch_prefix}{state['issue'].short_id.lower()}-{uuid.uuid4().hex[:8]}"


def _pr_title(state: BugOpsState) -> str:
    issue = state["issue"]
    return f"Fix {issue.short_id}: {issue.title or issue.culprit or 'Sentry issue'}"


def _pr_body(state: BugOpsState) -> str:
    issue = state["issue"]
    hypotheses = state.get("hypotheses", [])
    hypothesis = hypotheses[-1] if hypotheses else None
    confidence = state.get("confidence") or 0.0
    lines = [
        f"Auto-generated by BugOps for [{issue.short_id}]({issue.url or ''}).",
        "",
        f"**Confidence:** {confidence:.2f}  **Risk:** {state.get('risk_category')}",
    ]
    if hypothesis:
        lines += ["", f"**Hypothesis:** {hypothesis['summary']}", "", hypothesis["reasoning"]]
    if state.get("test_attempts"):
        lines += ["", f"Tests passed: `{state['test_attempts'][-1]['command']}`"]
    return "\n".join(lines)


def _run_sync(state: BugOpsState, settings: Settings, gh: GitHubClient, approve: ApproveFn) -> BugOpsState:
    if state.get("route_decision") != "suggest_pr" or not settings.enable_pr_creation:
        return {}

    if not settings.pr_auto_approve and not approve(state):
        logger.info("open_pr_declined", issue=state["issue"].short_id)
        return {"errors": ["open_pr_declined"]}

    diff = state.get("current_diff")
    if not diff:
        return {"errors": ["open_pr_no_diff"]}

    repo = state["repo"]
    local = local_repo.ensure_clone(
        settings.git_cache_dir, repo["owner"], repo["name"], settings.github_token.get_secret_value()
    )
    branch_name = _branch_name(settings, state)
    dest = settings.sandbox_worktree_dir / f"{repo['owner']}__{repo['name']}__pr__{uuid.uuid4().hex[:8]}"
    worktree.create_worktree(local, state["release_sha"], dest)
    try:
        ok, stderr = worktree.apply_diff(dest, diff)
        if not ok:
            logger.warning("open_pr_apply_failed", error=stderr)
            return {"errors": [f"open_pr_apply_failed: {stderr}"]}

        worktree_repo = GitRepo(dest)
        branch_ops.create_branch(worktree_repo, branch_name)
        branch_ops.commit_all(worktree_repo, _pr_title(state))

        pushed, push_error = branch_ops.push_branch(
            worktree_repo, repo["owner"], repo["name"], branch_name, settings.github_token.get_secret_value()
        )
        if not pushed:
            logger.warning("open_pr_push_failed", error=push_error)
            return {"errors": [f"open_pr_push_failed: {push_error}"]}

        try:
            pr_url = gh.create_pull_request(
                repo["owner"],
                repo["name"],
                title=_pr_title(state),
                body=_pr_body(state),
                head=branch_name,
                base=repo["default_branch"],
                draft=settings.pr_draft,
            )
        except Exception as exc:  # noqa: BLE001 — GitHub API boundary; degrade to an error, not a crash
            logger.warning("open_pr_github_api_failed", error=str(exc))
            return {"errors": [f"open_pr_github_api_failed: {exc}"]}

        logger.info("open_pr_created", pr_url=pr_url, branch=branch_name)
        return {"pr_url": pr_url}
    finally:
        worktree.remove_worktree(local, dest)


async def run(
    state: BugOpsState, settings: Settings, gh: GitHubClient, approve: ApproveFn = default_approve
) -> BugOpsState:
    return await asyncio.to_thread(_run_sync, state, settings, gh, approve)


__all__ = ["default_approve", "run"]
